.TH "src/bsort.f90" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bsort.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "module \fBbsort\fP"
.br
.ti -1c
.RI "interface \fBbsort::is_sorted\fP"
.br
.ti -1c
.RI "interface \fBbsort::is_sorted_asc\fP"
.br
.ti -1c
.RI "interface \fBbsort::is_sorted_dec\fP"
.br
.ti -1c
.RI "interface \fBbsort::swap\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
