.TH "bsort" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsort \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBis_sorted\fP"
.br
.ti -1c
.RI "interface \fBis_sorted_asc\fP"
.br
.ti -1c
.RI "interface \fBis_sorted_dec\fP"
.br
.ti -1c
.RI "interface \fBswap\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "integer, save, private \fBmax_interchange_sort_size\fP = 20"
.br
.RI "\fIThe maximium length of a vector to be sorted using an interchange sort\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file bsort\&.f90\&.
.SH "Member Data Documentation"
.PP 
.SS "integer, save, private bsort::max_interchange_sort_size = 20\fC [private]\fP"

.PP
Definition at line 8 of file bsort\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
