.TH "src/interchange_sort_vec_asc_dble.f90" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/interchange_sort_vec_asc_dble.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "pure subroutine \fBinterchange_sort_vec_asc_error_dble\fP (vec)"
.br
.RI "\fIRun an interchange sort on a vector of double precision values\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "pure subroutine interchange_sort_vec_asc_error_dble (double precision, dimension(:), intent(inout)vec)"
Run an interchange sort on a vector of double precision values\&.
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP The vector to be sorted\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
07/07/2014 
.RE
.PP

.PP
Definition at line 14 of file interchange_sort_vec_asc_dble\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
