.TH "Is_sorted" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Is_sorted \- 
.PP
Checks if a vector is sorted\&.  

.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "pure function \fBis_sorted_vec_dble\fP (vec, ascending)"
.br
.RI "\fIChecks if a vector is sorted\&. \fP"
.ti -1c
.RI "logical function \fBis_sorted_vec_gen_dble\fP (vec, ord)"
.br
.RI "\fICheck if a vector of double precision values is sorted by the specified order\&. \fP"
.ti -1c
.RI "logical function \fBis_sorted_vec_gen_int\fP (vec, ord)"
.br
.RI "\fICheck if a vector of integer values is sorted by the specified order\&. \fP"
.ti -1c
.RI "logical function \fBis_sorted_vec_gen_real\fP (vec, ord)"
.br
.RI "\fICheck if a vector of real values is sorted by the specified order\&. \fP"
.ti -1c
.RI "pure function \fBis_sorted_vec_int\fP (vec, ascending)"
.br
.RI "\fIChecks if a vector is sorted\&. \fP"
.ti -1c
.RI "pure function \fBis_sorted_vec_real\fP (vec, ascending)"
.br
.RI "\fIChecks if a vector is sorted\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Checks if a vector is sorted\&.
.PP
\fBReturn values:\fP
.RS 4
\fIsorted\fP Indicated if the vector vec is sorted in the specified order\&.
.RE
.PP
Value Meaning  T The vector is sorted F The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The vector to be sorted\&.
.br
\fIsort_type\fP Indicates the ordering to be checked for\&. The default value is 'A'\&. If an invalid value is passed, than a value of not sorted is returned\&.
.RE
.PP
Value Meaning  A Ascending order F Decending order 
.PP
\fBNote:\fP
.RS 4
In prior versions of this function, an interger was returns instread of a logical\&. If the vector was not sorted, than the interger would indicate the position of the first two pairwise elements where one element was larger than the following element\&. This proved to not be useful and was taken out\&. If need for this functionally is determined in the future, than it has been decided that it will be implimented in a different function, most likely wrapped in the same interface\&.
.PP
An empty vector is considered sorted\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
01/07/2014 
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "pure function is_sorted_vec_dble (double precision, dimension(:), intent(in)vec, logical, intent(in)ascending)"
Checks if a vector is sorted using a specified ordering\&.
.PP
\fBReturn values:\fP
.RS 4
\fIis_sorted\fP Indicated if the vector is sorted in the specified order\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP The vector to be checked\&.
.br
\fIascending\fP Indicates if the ordering to be checked for is in ascending or decending\&.
.RE
.PP
Value Meaning  true Ascending order false Decending order 
.PP
\fBNote:\fP
.RS 4
An empty or single value vector is considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The target of is not checked within the function, care should be used that the target functon is of the right form\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
06/07/2014 
.RE
.PP

.PP
Definition at line 37 of file is_sorted_vec_dble\&.f90\&.
.PP
References is_sorted_vec_asc_dble(), and is_sorted_vec_dec_dble()\&.
.SS "logical function is_sorted_vec_gen_dble (double precision, dimension(:), intent(in)vec, procedure(logical)ord)"
Check if a vector of double precision values is sorted by the specified order\&. Returns a logical value indicating if the vector is sorted\&.
.PP
\fBReturns:\fP
.RS 4
is_sorted Indicates if the vector is sorted\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP Te vec to be checked for being sorted\&.
.br
\fIord\fP A logical function which describes the ordering used\&. The function must take two double precision arguments and return true if and only if the first argument must proceed the second argument in the order\&.
.RE
.PP
\fBNote:\fP
.RS 4
Empty and single value vectors are considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The argument types and counts of ord are not checked within this function\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
05/07/2014 
.RE
.PP

.PP
Definition at line 31 of file is_sorted_vec_gen_dble\&.f90\&.
.SS "logical function is_sorted_vec_gen_int (integer, dimension(:), intent(in)vec, procedure(logical)ord)"
Check if a vector of integer values is sorted by the specified order\&. Returns a logical value indicating if the vector is sorted\&.
.PP
\fBReturns:\fP
.RS 4
is_sorted Indicates if the vector is sorted\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP Te vec to be checked for being sorted\&.
.br
\fIord\fP A logical function which describes the ordering used\&. The function must take two integer arguments and return true if and only if the first argument must proceed the second argument in the order\&.
.RE
.PP
\fBNote:\fP
.RS 4
Empty and single value vectors are considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The argument types and counts of ord are not checked within this function\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
05/07/2014 
.RE
.PP

.PP
Definition at line 31 of file is_sorted_vec_gen_int\&.f90\&.
.SS "logical function is_sorted_vec_gen_real (real, dimension(:), intent(in)vec, procedure(logical)ord)"
Check if a vector of real values is sorted by the specified order\&. Returns a logical value indicating if the vector is sorted\&.
.PP
\fBReturns:\fP
.RS 4
is_sorted Indicates if the vector is sorted\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP Te vec to be checked for being sorted\&.
.br
\fIord\fP A logical function which describes the ordering used\&. The function must take two real arguments and return true if and only if the first argument must proceed the second argument in the order\&.
.RE
.PP
\fBNote:\fP
.RS 4
Empty and single value vectors are considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The argument types and counts of ord are not checked within this function\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
05/07/2014 
.RE
.PP

.PP
Definition at line 31 of file is_sorted_vec_gen_real\&.f90\&.
.SS "pure function is_sorted_vec_int (integer, dimension(:), intent(in)vec, logical, intent(in)ascending)"
Checks if a vector is sorted using a specified ordering\&.
.PP
\fBReturn values:\fP
.RS 4
\fIis_sorted\fP Indicated if the vector is sorted in the specified order\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP The vector to be checked\&.
.br
\fIascending\fP Indicates if the ordering to be checked for is in ascending or decending\&.
.RE
.PP
Value Meaning  true Ascending order false Decending order 
.PP
\fBNote:\fP
.RS 4
An empty or single value vector is considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The target of is not checked within the function, care should be used that the target functon is of the right form\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
06/07/2014 
.RE
.PP

.PP
Definition at line 37 of file is_sorted_vec_int\&.f90\&.
.PP
References is_sorted_vec_asc_int(), and is_sorted_vec_dec_int()\&.
.SS "pure function is_sorted_vec_real (real, dimension(:), intent(in)vec, logical, intent(in)ascending)"
Checks if a vector is sorted using a specified ordering\&.
.PP
\fBReturn values:\fP
.RS 4
\fIis_sorted\fP Indicated if the vector is sorted in the specified order\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP The vector to be checked\&.
.br
\fIascending\fP Indicates if the ordering to be checked for is in ascending or decending\&.
.RE
.PP
Value Meaning  true Ascending order false Decending order 
.PP
\fBNote:\fP
.RS 4
An empty or single value vector is considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The target of is not checked within the function, care should be used that the target functon is of the right form\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
06/07/2014 
.RE
.PP

.PP
Definition at line 37 of file is_sorted_vec_real\&.f90\&.
.PP
References is_sorted_vec_asc_real(), and is_sorted_vec_dec_real()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
