.TH "src/is_sorted_vec_int.f90" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/is_sorted_vec_int.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "pure function \fBis_sorted_vec_int\fP (vec, ascending)"
.br
.RI "\fIChecks if a vector is sorted\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "pure function is_sorted_vec_int (integer, dimension(:), intent(in)vec, logical, intent(in)ascending)"
Checks if a vector is sorted using a specified ordering\&.
.PP
\fBReturn values:\fP
.RS 4
\fIis_sorted\fP Indicated if the vector is sorted in the specified order\&.
.RE
.PP
Value Meaning  true The vector is sorted false The vector is not sorted 
.PP
\fBParameters:\fP
.RS 4
\fIvec\fP The vector to be checked\&.
.br
\fIascending\fP Indicates if the ordering to be checked for is in ascending or decending\&.
.RE
.PP
Value Meaning  true Ascending order false Decending order 
.PP
\fBNote:\fP
.RS 4
An empty or single value vector is considered sorted\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The target of is not checked within the function, care should be used that the target functon is of the right form\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
06/07/2014 
.RE
.PP

.PP
Definition at line 37 of file is_sorted_vec_int\&.f90\&.
.PP
References is_sorted_vec_asc_int(), and is_sorted_vec_dec_int()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
