.TH "src/swap_int.f90" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/swap_int.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "pure subroutine \fBswap_int\fP (x, y)"
.br
.RI "\fISwap two integer values\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "pure subroutine swap_int (integer, intent(inout)x, integer, intent(inout)y)"
Swap two integer values\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The first value to be swapped\&.
.br
\fIy\fP The second value to be swapped\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
05/07/2014 
.RE
.PP

.PP
Definition at line 17 of file swap_int\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
