.TH "src/swap_vec_dble.f90" 3 "Mon Jul 7 2014" "Version 1.0" "BSort" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/swap_vec_dble.f90 \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "pure subroutine \fBswap_vec_dble\fP (vec, x, y)"
.br
.RI "\fISwap two values in #DATA_DOCREF# vector\&. \fP"
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "pure subroutine swap_vec_dble (double precision, dimension(:), intent(inout)vec, integer, intent(in)x, integer, intent(in)y)"
Swap two values in #DATA_DOCREF# vector\&.
.PP
\fBParameters:\fP
.RS 4
\fIx\fP The index of the first value to be swapped\&.
.br
\fIy\fP The index of the second value to be swapped\&.
.RE
.PP
\fBWarning:\fP
.RS 4
The values of x and y are not checked to be inside vec\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Arin R\&. Bratt 
.RE
.PP
\fBDate:\fP
.RS 4
07/07/2014 
.RE
.PP

.PP
Definition at line 20 of file swap_vec_dble\&.f90\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BSort from the source code\&.
