Is_sorted_asc
Functions/Subroutines
pure function is_sorted_vec_asc_dble (vec)
Check if a vector of double precision values is sorted by an ascending order.
pure function is_sorted_vec_asc_int (vec)
Check if a vector of integer values is sorted by an ascending order.
pure function is_sorted_vec_asc_real (vec)
Check if a vector of real values is sorted by an ascending order.
Detailed Description
Function/Subroutine Documentation
pure function is_sorted_vec_asc_dble (double precision, dimension(:), intent(in) vec)
Check if a vector of double precision values is sorted by an ascending order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
Note
Empty and single value vectors are considered sorted.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 25 of file is_sorted_vec_asc_dble.f90.
Referenced by is_sorted_vec_dble().
pure function is_sorted_vec_asc_int (integer, dimension(:), intent(in) vec)
Check if a vector of integer values is sorted by an ascending order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
Note
Empty and single value vectors are considered sorted.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 25 of file is_sorted_vec_asc_int.f90.
Referenced by is_sorted_vec_int().
pure function is_sorted_vec_asc_real (real, dimension(:), intent(in) vec)
Check if a vector of real values is sorted by an ascending order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
Note
Empty and single value vectors are considered sorted.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 25 of file is_sorted_vec_asc_real.f90.
Referenced by is_sorted_vec_real().