Is_sorted
Checks if a vector is sorted.
Functions/Subroutines
pure function is_sorted_vec_dble (vec, ascending)
Checks if a vector is sorted.
logical function is_sorted_vec_gen_dble (vec, ord)
Check if a vector of double precision values is sorted by the specified order.
logical function is_sorted_vec_gen_int (vec, ord)
Check if a vector of integer values is sorted by the specified order.
logical function is_sorted_vec_gen_real (vec, ord)
Check if a vector of real values is sorted by the specified order.
pure function is_sorted_vec_int (vec, ascending)
Checks if a vector is sorted.
pure function is_sorted_vec_real (vec, ascending)
Checks if a vector is sorted.
Detailed Description
Checks if a vector is sorted.
Return values
sorted Indicated if the vector vec is sorted in the specified order.
Value Meaning
T The vector is sorted
F The vector is not sorted
Parameters
x The vector to be sorted.
sort_type Indicates the ordering to be checked for. The default value is 'A'. If an invalid value is passed, than a value of not sorted is returned.
Value Meaning
A Ascending order
F Decending order
Note
In prior versions of this function, an interger was returns instread of a logical. If the vector was not sorted, than the interger would indicate the position of the first two pairwise elements where one element was larger than the following element. This proved to not be useful and was taken out. If need for this functionally is determined in the future, than it has been decided that it will be implimented in a different function, most likely wrapped in the same interface.
An empty vector is considered sorted.
Author
Arin R. Bratt
Date
01/07/2014
Function/Subroutine Documentation
pure function is_sorted_vec_dble (double precision, dimension(:), intent(in) vec, logical, intent(in) ascending)
Checks if a vector is sorted using a specified ordering.
Return values
is_sorted Indicated if the vector is sorted in the specified order.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec The vector to be checked.
ascending Indicates if the ordering to be checked for is in ascending or decending.
Value Meaning
true Ascending order
false Decending order
Note
An empty or single value vector is considered sorted.
Warning
The target of is not checked within the function, care should be used that the target functon is of the right form.
Author
Arin R. Bratt
Date
06/07/2014
Definition at line 37 of file is_sorted_vec_dble.f90.
References is_sorted_vec_asc_dble(), and is_sorted_vec_dec_dble().
logical function is_sorted_vec_gen_dble (double precision, dimension(:), intent(in) vec, procedure(logical) ord)
Check if a vector of double precision values is sorted by the specified order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
ord A logical function which describes the ordering used. The function must take two double precision arguments and return true if and only if the first argument must proceed the second argument in the order.
Note
Empty and single value vectors are considered sorted.
Warning
The argument types and counts of ord are not checked within this function.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 31 of file is_sorted_vec_gen_dble.f90.
logical function is_sorted_vec_gen_int (integer, dimension(:), intent(in) vec, procedure(logical) ord)
Check if a vector of integer values is sorted by the specified order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
ord A logical function which describes the ordering used. The function must take two integer arguments and return true if and only if the first argument must proceed the second argument in the order.
Note
Empty and single value vectors are considered sorted.
Warning
The argument types and counts of ord are not checked within this function.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 31 of file is_sorted_vec_gen_int.f90.
logical function is_sorted_vec_gen_real (real, dimension(:), intent(in) vec, procedure(logical) ord)
Check if a vector of real values is sorted by the specified order. Returns a logical value indicating if the vector is sorted.
Returns
is_sorted Indicates if the vector is sorted.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec Te vec to be checked for being sorted.
ord A logical function which describes the ordering used. The function must take two real arguments and return true if and only if the first argument must proceed the second argument in the order.
Note
Empty and single value vectors are considered sorted.
Warning
The argument types and counts of ord are not checked within this function.
Author
Arin R. Bratt
Date
05/07/2014
Definition at line 31 of file is_sorted_vec_gen_real.f90.
pure function is_sorted_vec_int (integer, dimension(:), intent(in) vec, logical, intent(in) ascending)
Checks if a vector is sorted using a specified ordering.
Return values
is_sorted Indicated if the vector is sorted in the specified order.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec The vector to be checked.
ascending Indicates if the ordering to be checked for is in ascending or decending.
Value Meaning
true Ascending order
false Decending order
Note
An empty or single value vector is considered sorted.
Warning
The target of is not checked within the function, care should be used that the target functon is of the right form.
Author
Arin R. Bratt
Date
06/07/2014
Definition at line 37 of file is_sorted_vec_int.f90.
References is_sorted_vec_asc_int(), and is_sorted_vec_dec_int().
pure function is_sorted_vec_real (real, dimension(:), intent(in) vec, logical, intent(in) ascending)
Checks if a vector is sorted using a specified ordering.
Return values
is_sorted Indicated if the vector is sorted in the specified order.
Value Meaning
true The vector is sorted
false The vector is not sorted
Parameters
vec The vector to be checked.
ascending Indicates if the ordering to be checked for is in ascending or decending.
Value Meaning
true Ascending order
false Decending order
Note
An empty or single value vector is considered sorted.
Warning
The target of is not checked within the function, care should be used that the target functon is of the right form.
Author
Arin R. Bratt
Date
06/07/2014
Definition at line 37 of file is_sorted_vec_real.f90.
References is_sorted_vec_asc_real(), and is_sorted_vec_dec_real().